### ISSUE TITLE
Locking / Delaying Launching App Change on main screen

### ISSUE THREAD

**Issue by goodplanet2012** [alescdb/LauncherTV#2] opened 2017-11-15 15:54 UTC
I second that lock feature!:) I made box for grandma and she always accidentally screw icons. I say check box in setting to lock icons is such a good idea! I made box for grandma and she always accidentally screw up icons. And it's true - it's so easy to get screw launch icons:) Player is very simple and great idea for older people :)

THE IDEA to make it easier: There could be done also in the way that you have to hold 5-10 seconds in order to get in the app list and change launch icon. Any idea is it possible to do? I could send donation if you would do that!:)

**Comment by alescdb** [comment] 2017-11-16 11:20
Duplicate of #1

**Closed by alescdb** 2017-11-16 11:20 UTC
